# COMP1531 Project search
# Written by Eric Lin z5257305
# 24/10/19

# Given a query string, return a collection of messages that match the query
def search(token, query_str):
   try:
        u_id, token_valid = validate_token(token)
    except ValueError:
        raise ValueError("Token was not generated by server!")
    if not token_valid:
        raise TokenError("Token is invalid!")

    user = db_get_user_by_u_id(u_id)
    user_channels = user.get_channels()

    search_messages = []
    for user_channel in user_channels:
        start = 0
        while start != -1: 
            channel_messages = channel_messages(token, user_channel, start)
            for channel_message in channel_messages['messages']:
                if query_str in message['message']:
                    search_messages.append(channel_message)
            start = channel_messages['end'] + 1
    return {'messages': search_messages}